### ISSUE TITLE
error in resolvePath in fiwareDeviceSimulatorCLI

### ISSUE THREAD

**Issue by alvarosainzpardo** [telefonicaid/fiware-device-simulator#50]
Because of the implementation of this function in the case the path is relative, the configuration file can only be inside the ROOT_PATH. For example, this command is not accepted even when it is correct:

```
$ fiwareDeviceSimulatorCLI -c ../<dir1>/<config_file.json>
```

The function assumes that a relative path is always this way: `./<path>` when the first character of the path is "."

**Comment by AlvaroVega** [comment]
According with doc:
```
    -c, --configuration <configuration-file-path>  Absolute or relative path (from the root of the Node application) to the device simulator configuration file (mandatory)
```
so if you are in ./bin you can run:
```
 fiwareDeviceSimulatorCLI -c ./<dir1>/<config_file.json>
```
